import pygame as _pg

# screen
FILE_TILE_SIZE = 16
TILE_SCALE = 4
TILE_SIZE = FILE_TILE_SIZE * TILE_SCALE
MAX_FPS = 60
WIDTH = 16 * TILE_SIZE
HEIGHT = 9 * TILE_SIZE
TILE = TILE_SIZE, TILE_SIZE
SCREEN_CENTER = _pg.Vector2(WIDTH // 2, HEIGHT // 2)

# camera
CAMERA_TOLERANCE_BORDER = 100
CAMERA_TOLERANCE = _pg.Rect(0, 0, WIDTH - CAMERA_TOLERANCE_BORDER * 2, HEIGHT - CAMERA_TOLERANCE_BORDER * 2)
CAMERA_TOLERANCE.center = SCREEN_CENTER
CAMERA_SPEED = 0.25
CAMERA_RANGE = 300
